### ISSUE TITLE
timeout issues while deploying Postgres flex database instance with terraform

### ISSUE THREAD

**Issue by docbyte86** [stackitcloud/terraform-provider-stackit#101]
Hello all,

we randomly get timeout issues while deploying Postgres flex databases with terraform.

│ Error: Error creating instance
│ 
│   with module.db.stackit_postgresflex_instance.database,
│   on .terraform/modules/db/main.tf line 5, in resource "stackit_postgresflex_instance" "database":
│    5: resource "stackit_postgresflex_instance" "database" {
│ 
│ Instance creation waiting: WaitWithContext() has timed out

After a while the instance get active in the portal but the state file of terraform remain locked.
Is it possible to get add a timeout parameter to increase the limit?

Something like

> resource "example_thing" "example" {
>
>  timeouts {
>    create = "60m"
>  }
>}

[Resources - Retries and Customizable Timeouts](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts)

**Comment by joaopalet** [comment]
Hello,

Thanks a lot for the suggestion! We will look into it.

For the moment, we will increase the timeouts so they don't happen so regularly.

**Comment by docbyte86** [comment]
Thank you very much. I see that you increased the timeout for a lot of services. many thanks! afaik we faced the issue on the SKE, as weel. Therefore, thank you very much for the quick win. will test tomorrow and let you know the results. Is it already a part of provider release version 0.6.0?

**Comment by joaopalet** [comment]
Hi,

We have just released a new version containing those changes: [v0.6.1](https://github.com/stackitcloud/terraform-provider-stackit/releases/tag/v0.6.1).
