### ISSUE TITLE
stackit_ske_cluster: invalid cluster name -> too long

### ISSUE THREAD

**Issue by docbyte86** [stackitcloud/terraform-provider-stackit#125]
Good morning,

i am trying to deploy SKE with terraform but getting error, pointing to the value of the name:

> stackit_ske_cluster.ske: Creating...
╷
│ Error: Error creating/updating cluster
│ 
│   with stackit_ske_cluster.ske,
│   on main.tf line 14, in resource "stackit_ske_cluster" "ske":
│   14: resource "stackit_ske_cluster" "ske" {
│ 
│ Calling API: 400 Bad Request, status code 400, Body: {"code":"InvalidArgument","message":"invalid input: cluster with name sbxske: Too long: must have at most 15 bytes\n","details":""}

```
resource "stackit_ske_cluster" "ske" {
  project_id         = "****"
  name               = "sbxske"
  kubernetes_version = "1.25"
  node_pools = [
    {
      os_version         = "3602.2.1"
      name               = "pool-groot-sbx01"
      machine_type       = "c1.3"
      max_surge          = 1
      max_unavailable    = 1
      minimum            = 2
      maximum            = 4
      volume_type        = "storage_premium_perf1"
      volume_size_gb     = 20
      availability_zones = ["eu01-3"]
      labels = {
        stage = "sbx",
        pool  = "pool-1"
      }
    }
  ]
  maintenance = {
    enable_kubernetes_version_updates    = true
    enable_machine_image_version_updates = true
    start                                = "01:00:00Z"
    end                                  = "02:00:00Z"
  }
  extensions = {
    acl = {
      allowed_cidrs = ["0.0.0.0/0"]
      enabled       = true
    }
    argus = {
      enabled = false
    }
  }
}
```

The name sbxske seems to be in the valid range. Can somebody support here, please? Many thanks in advance

**Comment by vicentepinto98** [comment]
Hello @docbyte86,
Thanks for raising the issue.

The error message returned by the API is misleading. 

The name of the `node_pool` that you are providing (`pool-groot-sbx01`) is the one that is too long.

Set a shorter name under `node_pools[0].name`.
