### ISSUE TITLE
Value Conversion Error stackit_ske_cluster extensions object

### ISSUE THREAD

**Issue by Passe-cc** [stackitcloud/terraform-provider-stackit#126]
Hello

I encountered the following error when using the provider:

>  Error: Value Conversion Error
│ 
│   with module.ske-cluster.stackit_ske_cluster.ske_cluster,
│   on ../main.tf line 24, in resource "stackit_ske_cluster" "ske_cluster":
│   24:   extensions                  = var.extensions
│ 
│ An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
│ 
│ Received unknown value, however the target type cannot handle unknown values. Use the corresponding `types` package type or a custom type that handles unknown values.
│ 
│ Path: extensions
│ Target Type: *ske.Extensions
│ Suggested Type: basetypes.ObjectValue

### **Steps to Reproduce**
1. create a terraform module for stackit_ske_cluster

**Resource:**
``` yaml
resource "stackit_ske_cluster" "ske_cluster" {
  project_id         = var.project_id
  name               = var.name
  node_pools         = var.node_pools
  extensions         = var.extensions
  ...
```
**variable:**
``` yaml
variable "extensions" {
  type = object({
    acl = optional(object({
      allowed_cidrs = list(string)
      enabled       = bool
    }))
    argus = optional(object({
      enabled           = bool
      argus_instance_id = string
    }))
  })
  default = null
}
```
2. run terraform init & terraform plan

### **Additional Information**
- Provider version:  0.6.2
- Terraform version: 1.5.7

**Comment by vicentepinto98** [comment]
Thank you for opening this issue.
This has been fixed in the v0.6.4 release.
