### ISSUE TITLE
0.6.5 stackit_argus_instance/Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by docbyte86** [stackitcloud/terraform-provider-stackit#134]
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.ske.stackit_ske_cluster.ske, provider
│ "provider[\"registry.terraform.io/stackitcloud/stackit\"]" produced an
│ unexpected new value: .hibernations: was
│ cty.ListValEmpty(cty.Object(map[string]cty.Type{"end":cty.String,
│ "start":cty.String, "timezone":cty.String})), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

+

│ When applying changes to module.ske.stackit_ske_cluster.ske, provider "provider[\"registry.terraform.io/stackitcloud/stackit\"]" produced an unexpected new value: .extensions: was cty.ObjectVal(map[string]cty.Value{"acl":cty.ObjectVal(map[string]cty.Value{"allowed_cidrs":cty.ListVal([]cty.Value{cty.StringVal("null")}),
│ "enabled":cty.False}), "argus":cty.ObjectVal(map[string]cty.Value{"argus_instance_id":cty.NullVal(cty.String), "enabled":cty.False})}), but now null.

Terraform will perform the following actions:

  # module.ske.stackit_ske_cluster.ske will be created
  + resource "stackit_ske_cluster" "ske" {
      + extensions              = {
          + acl   = {
              + allowed_cidrs = [
                  + "null",
                ]
              + enabled       = false
            }
          + argus = {
              + enabled = false
            }
        }
      + hibernations            = []
      + id                      = (known after apply)
      + kube_config             = (sensitive value)
      + kubernetes_version      = "1.25"
      + kubernetes_version_used = (known after apply)
      + maintenance             = {
          + enable_kubernetes_version_updates    = true
          + enable_machine_image_version_updates = true
          + end                                  = "02:23:45Z"
          + start                                = "01:23:45Z"
        }
      + name                    = "abc123odd-s"
      + node_pools              = [
          + {
              + availability_zones = [
                  + "eu01-3",
                ]
              + cri                = "containerd"
              + labels             = {
                  + "pool"  = "pool-1"
                  + "stage" = "sbx"
                }
              + machine_type       = "c1.3"
              + max_surge          = 1
              + max_unavailable    = 1
              + maximum            = 4
              + minimum            = 2
              + name               = "groot-sbx01"
              + os_name            = "flatcar"
              + os_version         = "3602.2.1"
              + volume_size        = 20
              + volume_type        = "storage_premium_perf1"
            },
        ]
      + project_id              = "******"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

**Comment by vicentepinto98** [comment]
Hello,
This issue has been fixed in the v0.6.6 release.
