### ISSUE TITLE
Argus supports ACL by now

### ISSUE THREAD

**Issue by MB175** [stackitcloud/terraform-provider-stackit#136]
Argus supports ACL however the api is not integrated into the provider yet.

Can this be implemented ?

https://docs.api.stackit.cloud/documentation/argus/version/v1#tag/acl

**Comment by vicentepinto98** [comment]
Hello @MB175,
Thanks for opening this feature request.
We have that feature in our roadmap and will work on it soon.

**Comment by DiogoFerrao** [comment]
ACL is available in the newest [Release](https://registry.terraform.io/providers/stackitcloud/stackit/0.15.0)
