### ISSUE TITLE
Argus scrape config | optional saml2 parameter required

### ISSUE THREAD

**Issue by sammetb** [stackitcloud/terraform-provider-stackit#191]
Trying to create a resouce argus_scrapeconfig
https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/argus_scrapeconfig

Following the documentation is saml2 optional.
If I wouldn't use this parameter I would get this error

![image](https://github.com/stackitcloud/terraform-provider-stackit/assets/69624844/84593eb6-fd96-45be-92bf-9b9c7de1d919)

I used the latest version of the provider 0.7.1.
Adding the optional parameter to it would resolve the issue

**Comment by joaopalet** [comment]
Hello, 

Thanks for the feedback and for opening an issue! We will soon start working on the fix.

**Comment by joaopalet** [comment]
This issue is fixed in the [v0.9.2](https://github.com/stackitcloud/terraform-provider-stackit/releases/tag/v0.9.2) release.
