### ISSUE TITLE
wrong SKE cluster creation example

### ISSUE THREAD

**Issue by mouhsen-ibrahim** [stackitcloud/terraform-provider-stackit#202]
The provided example for SKE cluster creation is wrong and needs some fixing
```
resource "stackit_ske_cluster" "example" {
  project_id         = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  name               = "example-name"
  kubernetes_version = "1.25"
  node_pools = [
    {
      name               = "np-example"
      machine_type       = "b1.2"
      os_version         = "3510.2.5"
      minimum            = "2"
      maximum            = "3"
      availability_zones = ["eu01-3"]
    }
  ]
  maintenance = {
    enable_kubernetes_version_updates    = true
    enable_machine_image_version_updates = true
    start                                = "01:00:00Z"
    end                                  = "02:00:00Z"
  }
}
```
- The `os_version` must be updated to `3510.2.7`, the current one doesn't work
- The name is unacceptable according to the regex used to verify it is 12 characters long and the regex says it must be at most 11
- The used regex allows `-` at the end but the error message says it doesn't allow them
- The regex allows `-` in the name but the SKE API doesn't allow them and it looks like that it doesn't have a 11 character size limit.

**Comment by vicentepinto98** [comment]
The [v08.0 release](https://github.com/stackitcloud/terraform-provider-stackit/releases/tag/v0.8.0) removes the cluster name regex validation (which is now done solely by the SKE API). The example was also updated.
