### ISSUE TITLE
`stackit_mongodbflex_user`: Host should return just the host

### ISSUE THREAD

**Issue by JorTurFer** [stackitcloud/terraform-provider-stackit#257]
`host` field returns the connection data: 
```
 + mongodb_host = "mongodb://fake:*******@s-xxxx-xxxx-xxx.mongodb.eu01.onstackit.cloud:27017/stackit?authSource=stackit&tls=true&authMechanism=SCRAM-SHA-256"
``` 

This isn't always enough as I can require to change some connection parameters and now I can't.

The only option to have the host right now is doing 
```terraform
"s-${stackit_mongodbflex_instance.instance.instance_id}.mongodb.eu01.onstackit.cloud"
```
This works as a workaround but in the mid/long term, having a field for recovering the server host only would be nice as it will rely on the terrform provider to generate the correct host instead of by myself. 
As user, probably I won't be aware about related changes and upgrading the provider could be always good.

**Comment by JorTurFer** [comment]
In the same way, the host with **** hiding the secret doesn't makes sense as I can't use it for anything without adding more logic on top of it

**Comment by hcsa73** [comment]
Hello! Thanks for opening the issue
We'll double-check what's the usecase for showing the connection parameters, and apply this if it's a better suit

**Comment by FlrnFrmm** [comment]
I wanted to report this issue too, so it seems to still exist.
But I also discovered a (maybe) related issue.
According to the [documentation](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/mongodbflex_user) the `stackit_mongodbflex_user` should have a field `uri`. That field does not exist it seems.
Could it be that the current 'host' value should be uri and host is missing?

**Comment by vicentepinto98** [comment]
We introduced the `uri` field in the release [v0.30.0](https://github.com/stackitcloud/terraform-provider-stackit/releases/tag/v0.30.0) but it is only set upon creation, so if you have an existing resource it is not updated. 

Regarding the `host` field, we are checking with MongoDBFlex how we can properly fix it. We'll keep you updated on the status

**Comment by vicentepinto98** [comment]
The `host` field now returns only the host. As mentioned before, we also have the `uri` field where the connection string is set.

**Comment by FlrnFrmm** [comment]
Thank you @vicentepinto98 !
