### ISSUE TITLE
`stackit_dns_record_set` enforces a valid IP Address always

### ISSUE THREAD

**Issue by JorTurFer** [stackitcloud/terraform-provider-stackit#261]
`stackit_dns_record_set` can be used for multiple record types, and not all of them are IP Address (e.g: CNAME, TXT,..) but the resource requires always the IP validation:
https://github.com/stackitcloud/terraform-provider-stackit/blob/28907ba33e0a1211ff03ee5a44729d66eccf6ed2/stackit/internal/services/dns/recordset/resource.go#L154-L163

The problem is that the validation doesn't check if the type of the record requires it either:
https://github.com/stackitcloud/terraform-provider-stackit/blob/28907ba33e0a1211ff03ee5a44729d66eccf6ed2/stackit/internal/validate/validate.go#L59-L74

As result of this, I'm getting a validation error when I try to set a TXT record:
`Attribute records[0] value must be an IP address, got: v=spf1 a mx include:xxxxxxxxx ~all`
and almost the same for a CNAME record:
`Attribute records[0] value must be an IP address, got: xxxxxxxxxx.stackit.org`

**Comment by JorTurFer** [comment]
you can assign it to me. I'lll work on it asap xD

**Comment by vicentepinto98** [comment]
This issue is fixed on the [v0.13.0](https://github.com/stackitcloud/terraform-provider-stackit/releases/tag/v0.13.0) release.
