### ISSUE TITLE
Question:  SchwarzIT/terraform-provider-stackit or stackitcloud/terraform-provider-stackit

### ISSUE THREAD

**Issue by PeterStolz** [stackitcloud/terraform-provider-stackit#266]
Hello,
when searching for a STACKIT terraform provider I found that there is this provider and the [SchwarzIT/terraform-provider-stackit](https://github.com/SchwarzIT/terraform-provider-stackit). They seem similar but still have different versioning and development. Is this the official one or should I use the SchwarzIT one? Which one is better maintained?

**Comment by joaopalet** [comment]
Hi,

This one ([stackitcloud/stackit](https://registry.terraform.io/providers/stackitcloud/stackit/latest)) is the official STACKIT Terraform provider.

The [SchwarzIT/stackit](https://registry.terraform.io/providers/SchwarzIT/stackit/latest) is a community maintained provider that was created before the official one.

**Comment by vicentepinto98** [comment]
Hello @PeterStolz, this is the official STACKIT Terraform Provider and we will extend it with all of the existing and future STACKIT services, so you should use this one.

The other provider that you mentioned is developed and maintained by the STACKIT community within Schwarz IT and it was created before the official one existed. It is still being maintained as long as internal teams are using it, per their [README](https://github.com/SchwarzIT/terraform-provider-stackit?tab=readme-ov-file#terraform-provider-for-stackit)
