### ISSUE TITLE
Enhancment: Improve SKE objects

### ISSUE THREAD

**Issue by PeterStolz** [stackitcloud/terraform-provider-stackit#273]
I had some unexpected friction when creating a cluster via terraform.
Here is a list of points I noticed:
- When specifying an invalid kubernetes version I am not told which versions are available. If you do that check please log them so I don't need to try multiple times which one is the latest one. `│ Creating cluster config API payload: getting latest matching kubernetes version: provided version is not one of the available kubernetes versions`. For the versions in the node pool I had to go to the UI and look at the values in the dropdown. That is not the best DX.
- Resource type stackit_ske_cluster needs the id of a stackit_ske_project not a stackit_project_id. This should be better documented

**Comment by vicentepinto98** [comment]
Hello @PeterStolz, thanks for opening the issue and the suggestions. We have put this in our backlog and will try to tackle it soon, it should be relatively easy to do.

**Comment by vicentepinto98** [comment]
Regarding your second point, which `id` are you referring to?
`stackit_ske_cluster.project_id` should be set to a STACKIT project ID, so the current description of the field is accurate: [`STACKIT project ID to which the cluster is associated.`](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/ske_cluster#project_id)

The `stackit_ske_project` resource has a field `project_id` and a field `id` (internal Terraform resource identifier) but they should all have the same value. So you can either get the project ID from the project resource or set it directly.

Do you have an example where this didn't work?

**Comment by PeterStolz** [comment]
> Regarding your second point, which id are you referring to?

You are correct. I thought I needed the id of the `stackit_ske_project` and not the stackit `project_id` because I need to create a `stackit_ske_project` to be able to create a cluster. This is not explicitly mentioned in the `stackit_ske_cluster` docs so I got it working by creating an stackit_ske_project assuming its id was then needed(in case I have multiple ske_projects?). Looking into the terraform state the `id` and `project_id` are identical.

**Comment by vicentepinto98** [comment]
The `stackit_ske_project` resource allows you to enable the SKE service for your project, you can only have one per project. If you had already enabled the SKE service (e.g. through the Portal) then you wouldn't need to create this resource and you could just provide the `project_id` in the cluster configuration.

As the concept of service enablement is coming to STACKIT and will impact all services, we will probably move the enablement logic into the `stackit_ske_cluster` resource directly and deprecate `stackit_ske_project` in a future release.

**Comment by PeterStolz** [comment]
Thanks for the clarification. I agree that from a developer experience perspective it definitely makes sense to abstract `stackit_ske_project` away.

**Comment by GokceGK** [comment]
The` stackit_ske_project` resource is deprecated in the new terraform provider release [v0.15.0](https://registry.terraform.io/providers/stackitcloud/stackit/0.15.0).

Besides that, service enablement logic has been moved into the `stackit_ske_cluster` resource.

**Comment by PeterStolz** [comment]
Awesome. Thanks a lot for implementing!
