### ISSUE TITLE
Feature: Create redis with `stackit_redis_instance`

### ISSUE THREAD

**Issue by PeterStolz** [stackitcloud/terraform-provider-stackit#275]
Right now you need the `instance_id` of an existing redis instance in order to use `stackit_redis_instance`.
Ideally I can actually create a new Redis Instance with terraform on STACKIT. I think the same problem applies to `stackit_redis_credential`. There a `credential_id` is required.
Am I missing a resource, or is this not yet implemented?

**Comment by vicentepinto98** [comment]
The required fields for provisioning a redis `instance` are:
[name](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/redis_instance#name) (String) Instance name.
[plan_name](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/redis_instance#plan_name) (String) The selected plan name.
[project_id](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/redis_instance#project_id) (String) STACKIT project ID to which the instance is associated.
[version](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/redis_instance#version) (String) The service version.

No `instance_id` is required.

See [stackit_redis_instance documentation](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/redis_instance)

The required fields for provisioning redis `credential` are:
[instance_id](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/redis_credential#instance_id) (String) ID of the Redis instance.
[project_id](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/redis_credential#project_id) (String) STACKIT Project ID to which the instance is associated.

No `credentials_id` is required.

See [stackit_redis_credential documentation](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/redis_credential)

Are you getting some error?

**Comment by PeterStolz** [comment]
Thanks for the quick response, indeed this works they way you specified. I was looking at data resources.
