### ISSUE TITLE
Enhancment: set URI in `stackit_redis_credential` to use SSL and uri to sensitive

### ISSUE THREAD

**Issue by PeterStolz** [stackitcloud/terraform-provider-stackit#276]
Right no the `stackit_redis_credential` returns an uri using no ssl but you can enble ssl using `rediss://` instead of `redis://`

Rabbitmq already uses ssl with `amqps`.

Also password is marked as sensitive, but the uri is not. That pattern is consistent across all credentials resources i have used so far including mariadb, redis, rabbitmq.

**Comment by vicentepinto98** [comment]
Hi @PeterStolz, we are looking into it and will get back to you :)

**Comment by vicentepinto98** [comment]
Hello, 
I have asked our colleagues and the returned URI is already the SSL one, for all of the services that you mentioned. 
For redis specifically, you just need to provide the --tls suffix on the connection client, but the connection string is the same.

If you can provide more details of your setup, we can support you better.

**Comment by PeterStolz** [comment]
I know I can enable TLS for my redis connection using --tls. However there are a bunch of libraries that infer this based on the provided connection URI. Some don't support additional flags and rely entirely on the provided URI. Also `rediss` is an official URI scheme.
https://www.iana.org/assignments/uri-schemes/prov/rediss
From a security point of view, as stackit redis supports TLS it should be the default and I should not have to opt in to communicate securely.
Most developers will likely just use the provided uri and do not bother to enable tls on their redis client, as they expect secure defaults. The app I am working with only takes a redis URI as an environment variable meaning that I would have to do brittle string manipulation inside terraform to use secure communication.

I am confident that this is the exact reason that the rabbimq resource defaults to `amqps://` instad of `amqp://` which would also work. It is the same thing with http vs https. You would not post http links nowdays if the server can speak https as well

**Comment by vicentepinto98** [comment]
Thanks for the detailed reply, we will replace the redis URI and return `rediss`. We hope to work on that soon

**Comment by jebreuer** [comment]
Just ran into the same issue as well.

I tried to configure our app with a redis connection. The data from the terraform provider said the uri was `redis://...`. Connecting to that endpoint didn't work in our app so I tried with the redis-cli which just complained about an IO error. Luckily Peter sits across the room so I could ask him for his experience and he tells me that he also stumbled into the same problem and an issue is already open.

Sad to say but currently it's not fun. If you can't provide a fix in a timely manner please **update the documentation** accordingly so it at least saves other people's time.

**Comment by vicentepinto98** [comment]
This issue was fixed in the latest release of the provider [v0.18.0](https://github.com/stackitcloud/terraform-provider-stackit/releases/tag/v0.18.0)
