### ISSUE TITLE
Documentation: stackit_ske_cluster.project_id

### ISSUE THREAD

**Issue by jebreuer** [stackitcloud/terraform-provider-stackit#295]
The [Documentation](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/ske_cluster#project_id) says:
> (String) STACKIT project ID to which the cluster is associated.

But what actually is required is the corresponding [stackit_ske_project.id](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/ske_project#id)

It took me a while to figure that out by trial and error. If you just pass in the STACKIT Project Id it comes up with weird errors regarding authorization.

Kind regards

**Comment by joaopalet** [comment]
Hi @jebreuer,

This was already discussed in #273 (more specifically in https://github.com/stackitcloud/terraform-provider-stackit/issues/273#issuecomment-1961632766). 

In short, these should have the same value, and multiple [stackit_ske_project](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/ske_project) should not coexist at the same time. 

This resource is just used for enabling the SKE for a STACKIT project, and as you also pointed in another issue we should and will move the enablement logic into the `stackit_ske_cluster` resource directly and deprecate `stackit_ske_project` in a future release.

**Comment by GokceGK** [comment]
The` stackit_ske_project` resource is deprecated in the new terraform provider release [v0.15.0](https://registry.terraform.io/providers/stackitcloud/stackit/0.15.0).

Besides that, service enablement logic has been moved into the `stackit_ske_cluster` resource.
