### ISSUE TITLE
deleting a mariadb instance outside of terraform breaks planning

### ISSUE THREAD

**Issue by PeterStolz** [stackitcloud/terraform-provider-stackit#321]
Hi,
deleting a mariadb that is in state outside of terraform results in the following error instead of triggering a recration.
```
╷
│ Error: Error reading instance
│ 
│   with stackit_mariadb_instance.mariadb,
│   on main.tf line 173, in resource "stackit_mariadb_instance" "mariadb":
│  173: resource "stackit_mariadb_instance" "mariadb" {
│ 
│ Calling API: 410 Gone, status code 410, Body: {"error":"Get instance failed. instance deleted","description":""}
│ 
│ 
╵
```

I would expect the provider to recognise that the instance in state is gone and recreate it and its dependencies.
I work around it wit `tf state rm stackit_mariadb_instance.mariadb`, but it is not ideal that I have to touch the terraform state locally

**Comment by joaopalet** [comment]
Hi, 

Thanks for reporting the issue. This was addressed in the latest [v0.16.0](https://registry.terraform.io/providers/stackitcloud/stackit/0.16.0) release.
