### ISSUE TITLE
Create Computing Instance is missing

### ISSUE THREAD

**Issue by JonathanDeul** [stackitcloud/terraform-provider-stackit#34]
Hi, I was not able to find a possibility to create a computing instance via Terraform.
Is it just missing the example or is it really not possible to create a VM via Terraform? If so, will it be possible at some point in the future?
Thanks :)

**Comment by PhilippSeitz** [comment]
Hi Jonathan,

this is not supported by our official terraform provider yet. But we are on it to make it possible.

In the meantime you can use the [terraform-provider-openstack](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest) in conjunction with our [STACKIT Infrastructure API](https://docs.stackit.cloud/stackit/en/basic-concepts-infrastructureapi-10977435.html#BasicConceptsInfrastructureAPI-HashiCorpTerraform-ProviderforOpenStack) to automate VM creation in your projects.

**Comment by JonathanDeul** [comment]
Hi, tanks for the recommendation!

**Comment by vicentepinto98** [comment]
The [v0.33.0](https://github.com/stackitcloud/terraform-provider-stackit/releases/tag/v0.33.0) release of the provider supports a batch of IaaS resources, including `stackit_server.` We are happy to hear your feedback and will continue to extend the provider with more resources.
