### ISSUE TITLE
Storage Class Update is not possible on Postgres-Flex

### ISSUE THREAD

**Issue by roberth1988** [stackitcloud/terraform-provider-stackit#342]
Currently the provider has no `stringplanmodifier.RequiresReplace()` for the change of the storage class and the STACKIT API returns: `update functionalitynot supported for field 'class'`

This ends in a fail since the change can't be handled, but the provider suggests that it can be changed.

That's likely due bad design on the Postgres-flex API which suggests it can be updated.

**Comment by roberth1988** [comment]
This applies like also to the MongoDB.

**Comment by DiogoFerrao** [comment]
Thank you for the report @roberth1988!
I will be working on a fix for this today and provide an update once this issue is addressed.

**Comment by DiogoFerrao** [comment]
I just merged some changes to support this for Postgres-Flex. Regarding MongoDB, we are experiencing some issues that require further investigation.
Thank you again for reporting, this issue will remain open until we can produce a fix for MongoDB as well. Will provide updates on that soon.
