### ISSUE TITLE
Removing a nodepool in a multi-nodepool SKE cluster deletes wrong nodepool

### ISSUE THREAD

**Issue by maxbischoff** [stackitcloud/terraform-provider-stackit#372]
When removing a nodepool in the `node_pools` of a `stackit_ske_cluster`, that has other nodepools after it in the list, terraform generates a plan similar to this:

```
  # stackit_ske_cluster.api_cluster will be updated in-place
  ~ resource "stackit_ske_cluster" "api_cluster" {
        id                      = "<removed>"
      + kube_config             = (sensitive value)
      ~ kubernetes_version_used = "1.26.15" -> (known after apply)
        name                    = "apidev"
      ~ node_pools              = [
          ~ {
              ~ availability_zones = [
                  - "eu01-m",
                  + "eu01-1",
                  + "eu01-2",
                  + "eu01-3",
                ]
              ~ max_surge          = 1 -> 3
              ~ max_unavailable    = 1 -> 0
              ~ name               = "apidevnode" -> "nodepool"
                # (9 unchanged attributes hidden)
            },
          - {
              - availability_zones = [
                  - "eu01-1",
                  - "eu01-2",
                  - "eu01-3",
                ] -> null
              - cri                = "containerd" -> null
              - labels             = {} -> null
              - machine_type       = "m1.3" -> null
              - max_surge          = 1 -> null
              - max_unavailable    = 1 -> null
              - maximum            = 10 -> null
              - minimum            = 3 -> null
              - name               = "nodepool" -> null
              - os_name            = "flatcar" -> null
              - os_version         = "3815.2.1" -> null
              - volume_size        = 50 -> null
              - volume_type        = "storage_premium_perf1" -> null
            },
        ]
        # (4 unchanged attributes hidden)
    }
```

my nodepools were changed from

```hcl
  node_pools = [{
    name               = "apidevnode"
    machine_type       = "m1.3"
    max_surge          = "1"
    max_unavailable    = "1"
    maximum            = "10"
    minimum            = "3"
    volume_size        = "50"
    volume_type        = storage_premium_perf1
    os_version         = "3815.2.1"
    availability_zones = ["eu01-m"]
    }, {
    name            = "nodepool"
    machine_type    = "m1.3"
    max_surge       = "1"
    max_unavailable = "1"
    maximum         = "10"
    minimum         = "3"
    volume_size     = "50"
    volume_type     = storage_premium_perf1
    os_version      = "3815.2.1"
    availability_zones = ["eu01-1", "eu01-2", "eu01-3"]
  }]
  ```
  
  to 
  
  ```hcl
  node_pools = [{
    name            = "nodepool"
    machine_type    = "m1.3"
    max_surge       = "3"
    max_unavailable = "0"
    maximum         = "10"
    minimum         = "3"
    volume_size     = "50"
    volume_type     = storage_premium_perf1
    os_version      = "3815.2.1"
    availability_zones = ["eu01-1", "eu01-2", "eu01-3"]
  }]
  ```
  
  I would have expected the terraform provider to identify the nodepool by name and correctly remove the first nodepool (named `apidev`) and modify the second nodepool.
  
  Instead the provider seems to identify the nodepool by index in the array.

**Comment by maxbischoff** [comment]
A workaround for this issue is removing the nodepool in the Portal, this changes the plan to:

```
  # stackit_ske_cluster.api_cluster will be updated in-place
  ~ resource "stackit_ske_cluster" "api_cluster" {
        id                      = "<redacted>"
      + kube_config             = (sensitive value)
      ~ kubernetes_version_used = "1.26.15" -> (known after apply)
        name                    = "apidev"
      ~ node_pools              = [
          ~ {
              ~ max_surge          = 1 -> 3
              ~ max_unavailable    = 1 -> 0
                name               = "nodepool"
                # (10 unchanged attributes hidden)
            },
        ]
        # (4 unchanged attributes hidden)
    }
```

Which looks good to me.

**Comment by vicentepinto98** [comment]
Hi @maxbischoff, thanks for opening the issue. You're right, we should be matching the nodepool by name and not index in the array, I'll have a look.

Just to understand better your case, you removed the `apidevnode` **and** changed two fields (`max_surge` and `max_unavailable`) on `nodepool`, right?

**Comment by maxbischoff** [comment]
Yes, those were the changes I was doing. I guess for a minimal reproduction it would be enough to only remove the `apidevnode` pool.
I took a brief look at the [terraform provider development documentation](https://developer.hashicorp.com/terraform/plugin/framework/resources/plan-modification#prior-state-under-lists-and-sets), it seems like this might not be trivially possible with the current data structure though.

I think for using nodepools in `dynamic`  blocks it might be good to have nodepools be a [nested block](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/blocks/set-nested), although that would be a larger change.

**Comment by vicentepinto98** [comment]
We'll have a look and check what can be done. 
We also considered having nodepools as a separate resource, which would solve this issue, but that's currently not planned.

**Comment by vicentepinto98** [comment]
Hi @maxbischoff, after taking a deeper look into it, these are my takeaways:
- Even though the plan looks weird, the resource state in the end is correct, **there is no bug in terms of actual changes** to your cluster. We are sending the correct payload to the API
- This is indeed a shortcoming of the [terraform-plugin-framework] (https://developer.hashicorp.com/terraform/plugin/framework/resources/plan-modification#caveats) that we are using
- We won't use [nested blocks](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/blocks/set-nested), as those seem to have been disencouraged in favor of the nested attribute types, per the documentation: "Use [nested attribute types](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/attributes#nested-attribute-types) instead of block types for new schema implementations. Block support is mainly for migrating legacy SDK-based providers."

**Comment by maxbischoff** [comment]
Thanks for investigating and your feedback!

About your first point:
Which changes do you send to the API in this case? Do you delete the first nodepool and modify the second one? I guess in that case only the plan looks confusing, I would not feel comfortable applying that to a production cluster.

**Comment by maxbischoff** [comment]
I see, thanks a lot. I wasn't aware of the API structure in SKE. I guess in that case it might not be feasible or sensible to fix this on the provider side. Feel free to close this.
