### ISSUE TITLE
Error: Provider produced inconsistent result after apply (v0.18.0)

### ISSUE THREAD

**Issue by timethethyme** [stackitcloud/terraform-provider-stackit#374]
Hi all, 

after executing `tofu apply` the following error is thrown: 

> Error: Provider produced inconsistent result after apply
> 
>  When applying changes to stackit_ske_cluster.kubernetes_cluster, provider 
>  "provider[\"registry.opentofu.org/stackitcloud/stackit\"]" produced an unexpected new value: .network: was null, but now cty.ObjectVal(map[string]cty.Value{"id":cty.NullVal(cty.String)}).
>  
> This is a bug in the provider, which should be reported in the provider's own issue tracker. 

Used `main.tf` file
```yaml
terraform {
  required_providers {
    stackit = {
      source  = "stackitcloud/stackit"
      version = "0.18.0"
    }
}


resource "stackit_ske_cluster" "kubernetes_cluster" {
  project_id             = var.project_id
  name                   = "example-cluster"
  kubernetes_version_min = "1.28"
  node_pools             = [
    {
      name               = "example-node-pool"
      machine_type       = "b1.2"
      os_name            = "flatcar"
      os_version_min     = "3815.2.1"
      minimum            = 1
      maximum            = 2
      availability_zones = ["eu01-3"]
      volume_size        = 20
      volume_type        = "storage_premium_perf0"
    }
  ]
}
```

`tofu plan` prints the following: 

```
  # stackit_ske_kubeconfig.kubernetes_cluster_config will be created
  + resource "stackit_ske_kubeconfig" "kubernetes_cluster_config" {
      + cluster_name   = "example-cluster"
      + expiration     = 3600
      + expires_at     = (known after apply)
      + id             = (known after apply)
      + kube_config    = (sensitive value)
      + kube_config_id = (known after apply)
      + project_id     = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      + refresh        = true
    }
```

**Note: Error does not happen when downgrading to Version 0.17.0**

**Comment by vicentepinto98** [comment]
Hi @timethethyme, thanks for reporting the issue. We have just released a fix in the latest version [v0.18.1](https://github.com/stackitcloud/terraform-provider-stackit/releases/tag/v0.18.1)
