### ISSUE TITLE
Provider Produced Inconsistent Result After Apply When Using Stackit SKE with Local Terraform Module

### ISSUE THREAD

**Issue by RohitKolhe** [stackitcloud/terraform-provider-stackit#394]
**Description:**
When attempting to deploy the SKE using a local Terraform module, we encountered an error that did not occur when deploying the SKE resource directly.

**Environment:**
Stackit Version: ~> 0.18.1
Terraform Version: 1.8.0
Provider: registry.terraform.io/stackitcloud/stackit

**Error Details:**
When running terraform apply, we receive the following error message:

`│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.ske.stackit_ske_cluster.ske, provider
│ "provider[\"registry.terraform.io/stackitcloud/stackit\"]" produced an unexpected new value:
│ .node_pools[0].taints: was cty.ListValEmpty(cty.Object(map[string]cty.Type{"effect":cty.String,
│ "key":cty.String, "value":cty.String})), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.`

**Comment by GokceGK** [comment]
Hello @RohitKolhe, thanks for reporting the issue.
Could you please send us your configuration? We are currently investigating and trying to reproduce the issue.

**Comment by RohitKolhe** [comment]
#root module

resource "stackit_network" "vpc" {
  project_id = var.project_id
  name       = "test-vpc"
  nameservers = [
    "1.1.1.1",
    "8.8.8.8",
    "9.9.9.9"
  ]
  ipv4_prefix_length = 22
}

module "ske" {
  source                 = "../modules/stackit-kubernetes-cluster"
  name                   = var.kubernetes_cluster_name
  project_id             = var.project_id
  kubernetes_version_min = var.kubernetes_version_min #1.28.10
  maintenance = {
    enable_kubernetes_version_updates    = true
    enable_machine_image_version_updates = true
    start                                = "01:00:00Z"
    end                                  = "02:00:00Z"
  }
  network = {
    id = stackit_network.vpc.network_id
  }
  node_pools = [
    {
      name               = "system"
      machine_type       = "c1.2"
      minimum            = "1"
      maximum            = "3"
      availability_zones = ["eu01-1", "eu01-2", "eu01-3"]
    }
  ]
  extensions = {
    acl = {
      enabled       = true
      allowed_cidrs = var.allowed_cidrs
    }
  }
}


#local module resource

resource "stackit_ske_cluster" "ske" {
  
  name                      = var.name
  project_id                = var.project_id
  extensions                = var.extensions
  kubernetes_version_min    = var.kubernetes_version_min
  maintenance               = var.maintenance
  network                   = var.network
  node_pools                = var.node_pools
}

resource "stackit_ske_kubeconfig" "kubeconfig" {
  depends_on = [ stackit_ske_cluster.ske ]
  project_id   = var.project_id
  cluster_name = var.name
  refresh      = true
}

**Comment by DiogoFerrao** [comment]
Hey @RohitKolhe, do you have any updates on this?
We have since diagnosed and solved a bug related with the `taints` field (see #456). 

Maybe this also solved you case?

**Comment by joaopalet** [comment]
Hi @RohitKolhe,

We will close this issue due to inactivity. Feel free to re-open in case the issue persists!
