### ISSUE TITLE
PostgreSQL Flex resource for database creation

### ISSUE THREAD

**Issue by tchelovilar** [stackitcloud/terraform-provider-stackit#396]
Is it possible to add a resource to create databases on PostgreSQL Flex? Currently, I have to use Postgresql provider to connect to the instance and create the database.

Thanks

**Comment by roberth1988** [comment]
We need this feature also for an internal project. According to the STACKIT API its already possible to create/manage databases.

**Comment by joaopalet** [comment]
Hey @tchelovilar @roberth1988,

Thanks for the suggestion. Currently the database endpoints were not yet included in the [STACKIT SDK for Go](https://github.com/stackitcloud/stackit-sdk-go) by the PostgreSQL Flex team. We will discuss this with them and then plan the integration of the database resource

**Comment by malteehrlen** [comment]
We are eagerly awaiting this as well!

**Comment by tchelovilar** [comment]
The new version 0.24.2 supports the database creation. Thanks.
