### ISSUE TITLE
Provide more information on non-existing resources that got deleted in the backend

### ISSUE THREAD

**Issue by roberth1988** [stackitcloud/terraform-provider-stackit#398]
Hi guys,

just one example for the MongoDB:  https://github.com/stackitcloud/terraform-provider-stackit/blob/dc58d12cb9c4e893928dd199223fa04bb1e03684/stackit/internal/services/mongodbflex/user/resource.go#L267

```
	recordSetResp, err := r.client.GetUser(ctx, projectId, instanceId, userId).Execute()
	if err != nil {
		oapiErr, ok := err.(*oapierror.GenericOpenAPIError) //nolint:errorlint //complaining that error.As should be used to catch wrapped errors, but this error should not be wrapped
		if ok && oapiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		core.LogAndAddError(ctx, &resp.Diagnostics, "Error reading user", fmt.Sprintf("Calling API: %v", err))
		return
	}
```

It would be great to give the user some feedback, with changing it to:

```
	recordSetResp, err := r.client.GetUser(ctx, projectId, instanceId, userId).Execute()
	if err != nil {
		oapiErr, ok := err.(*oapierror.GenericOpenAPIError) //nolint:errorlint //complaining that error.As should be used to catch wrapped errors, but this error should not be wrapped
		if ok && oapiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
                        resp.Diagnostics.AddError("resource not found", err.Error()) // I GOT ADDED 
			return
		}
		core.LogAndAddError(ctx, &resp.Diagnostics, "Error reading user", fmt.Sprintf("Calling API: %v", err))
		return
	}
```

This should be applied to all cases, so you gonna give the user a better feedback if something got deleted using the portal or the API without TF.

Cheers
Rob

**Comment by joaopalet** [comment]
Hi @roberth1988,

The idea with this logic is that `terraform plan` does _not_ error when a resource in the state was deleted, and instead tries to recreate it. This was suggested in #300 and #321

**Comment by joaopalet** [comment]
HI @roberth1988,

I'll close this issue due to inactivity. Please feel free to re-open it if you still have questions!
