### ISSUE TITLE
postgres-flex documentation lacks information about supported roles

### ISSUE THREAD

**Issue by roberth1988** [stackitcloud/terraform-provider-stackit#399]
The documentation currently does not indicate which roles are supported: 

[roles](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs#roles) (Set of String)

Please document which are supported. Please also ensure that the role `create_db` will be supported.
So as a User I am able to create custom schemas.

**Comment by joaopalet** [comment]
Hi @roberth1988,

Thank for the request, we have created a story and will work on it soon.

**Comment by joaopalet** [comment]
Hi @roberth1988,

We have added documentation for the field and released this as part of [`v0.24.0`](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/postgresflex_user#roles).
