### ISSUE TITLE
handle Argus Alerts over Terrform

### ISSUE THREAD

**Issue by fasibio** [stackitcloud/terraform-provider-stackit#408]
Is there some plan to add terraform ressource to handle argus alters directly by terraform ?

**Comment by DiogoFerrao** [comment]
Hey @fasibio,
The Argus alerting setup (explained [here](https://docs.stackit.cloud/stackit/en/alerting-overview-step-by-step-129663400.html)) uses Prometheus and Alertmanager.
We currently have a plan to integrate the configuration of the Argus Alertmanager (routes and receivers) in the Terraform provider by the end of Q3 2024.
Regarding the integration of the Prometheus side (alert groups, records and rules), I cannot provide a concrete timeline but we are working towards having these included in the Provider as well.

Does this answer your question?

**Comment by DiogoFerrao** [comment]
Hey @fasibio, I'll close this issue due to inactivity. Please feel free to re-open it if you still have doubts!
