### ISSUE TITLE
[Question] SKE node_pool order important ?

### ISSUE THREAD

**Issue by JanGrosse** [stackitcloud/terraform-provider-stackit#419]
Hello,

I am using the terraform provider in the latest version (currently `v.0.19.0`).

When I define a `stackit_ske_cluster` and add a `node_pools` list this list seems to be required to keep the initial order.
Adding new items to the end of the list is working fine, but when you start to delete items from the "middle" of the list the terraform plan output seems like it is trying to keep everything "in-order".

Just as an example - I have the following configuration

```
resource "stackit_ske_cluster" "example-cluster" {
  name               = "example"
  project_id         = 1-2-3-4-5
  kubernetes_version = "1.28"
  node_pools = [
    {
      name         = "example-01"
      machine_type = "c1.3"
      minimum     = 1
      maximum     = 2
      os_version  = "3815.2.2"
      volume_size = 50
      volume_type = "storage_premium_perf2"
      availability_zones = ["eu01-1"]
    },
    {
      name         = "example-02"
      machine_type = "g1.4"
      minimum     = 1
      maximum     = 2
      os_version  = "3815.2.2"
      volume_size = 50
      volume_type = "storage_premium_perf2"
      availability_zones = ["eu01-1"]
    },
  ]
} 
```

If I run `terraform apply` all is great. But if I now go ahead and just reorder those two so it becomes this

```
resource "stackit_ske_cluster" "example-cluster" {
  name               = "example"
  project_id         = 1-2-3-4-5
  kubernetes_version = "1.28"
  node_pools = [
    {
      name         = "example-02"
      machine_type = "g1.4"
      minimum     = 1
      maximum     = 2
      os_version  = "3815.2.2"
      volume_size = 50
      volume_type = "storage_premium_perf2"
      availability_zones = ["eu01-1"]
    },
    {
      name         = "example-01"
      machine_type = "c1.3"
      minimum     = 1
      maximum     = 2
      os_version  = "3815.2.2"
      volume_size = 50
      volume_type = "storage_premium_perf2"
      availability_zones = ["eu01-1"]
    },
  ]
} 
```

and I execute a new `terraform plan` I expect no changes because I basically only changed the order of items. But the output implies that it would go ahead and recreate the first nodepool with new machine type etc.

```
  # stackit_ske_cluster.example-cluster will be updated in-place
  ~ resource "stackit_ske_cluster" "example-cluster" {137e6752a0aa
        name                    = "example"
      ~ node_pools              = [
          ~ {
              ~ machine_type       = "c1.3" -> "g1.4"
              ~ name                    = "example-01" -> "example-02"
                # (10 unchanged attributes hidden)
            },
          ~ {
              ~ machine_type       = "g1.4" -> "c1.3"
              ~ name                  ="example-02" -> "example-01"
                # (10 unchanged attributes hidden)
            },
        ]
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

I faced this issue with my other SKE cluster which contains 7 NodePools `[ is-01, sol-01, sol-02, sol-03, is-02, ut-01, ut-02]` (in this order).
I want to delete `sol-01, sol-02, sol-03` and expected no changes besides that it would delete 3 objects. But instead it would delete 3 objects ( `is-02, ut-01, ut-02`) and change 3 objects (change `sol-01` to match `is-02`, change `sol-02` to match `ut-01` etc.). And by change I mean it would change (as in my example above) machine-type, name, labels, availability zone etc. 

My question would simply be - is this really what is going to happen in the background ? Or is this just terraforms plan output and the provider catches those order issues and does not touch 6 different node_pools, just because I wanted to delete 3 which would change the order.

Greetings,
JanGrosse

**Comment by joaopalet** [comment]
Hi @JanGrosse,

Even though the plan looks strange, the correct payload is sent to the SKE API, which has a single [endpoint](https://docs.api.stackit.cloud/documentation/ske/version/v1#tag/Cluster/operation/SkeService_CreateOrUpdateCluster) for creating/updating a cluster. This receives the list of nodepools as an array of objects, and each nodepool is uniquely identified by its name.

This is a valid concern and was already raised here (#372), which seems to be a shortcoming of the [terraform-plugin-framework](https://developer.hashicorp.com/terraform/plugin/framework/resources/plan-modification#caveats). A possible workaround from our side would be to use nested blocks, but we won't do it as these were discouraged in favor of what was are using right now (as explained [here](https://github.com/stackitcloud/terraform-provider-stackit/issues/372#issuecomment-2133070299))

**Comment by JanGrosse** [comment]
Hi @joaopalet ,

thank you for the detailed informations. Okay, so I understood from the closed issue that only the terraform plan output looks strange and in the end the correct payload is send towards the SKE API. So as there is currently no feasable workaround would it make sense to add this kind of information into the provider documentation itself ? There might come additional colleagues facing the same output and starting to wonder what will happen if they apply the terraform plan output 😄 

But besides that my question is answered, thank you, I am going to close the issue.

Greetings,
JanGrosse.

**Comment by joaopalet** [comment]
Thanks for the suggestion @JanGrosse!
