### ISSUE TITLE
Terraform State on Service Update

### ISSUE THREAD

**Issue by BackInBash** [stackitcloud/terraform-provider-stackit#437]
Hi guys,

I'm not sure how the Terraform Provider is reacting if a Managed Service update occur.

Scenario:
I rolled out an Argus instance via terraform and it's in state -> `ACTIVE`
The instance get's an update (not via my terraform maybe from the product team) and the state is changed to -> `UPDATE_SUCCEEDED`
I now ran a terraform plan to see changes in my deployment.

The question now, is there an output and how would the Terraform provider react to it?

**Comment by BackInBash** [comment]
This is my Terraform plan output. There are no changes listed.
![tf_plan_argus copy](https://github.com/stackitcloud/terraform-provider-stackit/assets/48181660/674a47e6-443f-493d-ba54-1bf9deb8a069)

**Comment by GokceGK** [comment]
Hi @BackInBash , 

a similar issue has been reported to Terraform. https://github.com/hashicorp/terraform/issues/34144
They were able to identify and fix the issue. Could you please verify your Terraform version and update if possible? 
Please get in touch with us if problem persists after update.

**Comment by joaopalet** [comment]
Hey @BackInBash, I'll close this issue due to inactivity. Please feel free to re-open it if you still have doubts!
