### ISSUE TITLE
SKE Enablement logic fails on a fresh project for the first time

### ISSUE THREAD

**Issue by PeterStolz** [stackitcloud/terraform-provider-stackit#454]
Hi,
I am deploying to a "fresh" STACKIT project and the first time I ran my terraform script I got the following error:
```
╷
│ Error: Error creating cluster
│ 
│   with stackit_ske_cluster.ske,
│   on main.tf line 202, in resource "stackit_ske_cluster" "ske":
│  202: resource "stackit_ske_cluster" "ske" {
│ 
│ Wait for SKE enablement: 404 Not Found, status code 404, Body: {"code":"NotFound",
│ "message":"project id \"6d519696-52b3-45ac-9cc1-3d95831005aa\": not found", "details":""}
│ 
╵
```

Running it again the enablement logic seemed to work and it created the cluster successfully.

Expected behaviour:
It should run through without errors the first time.

**Comment by DiogoFerrao** [comment]
Hey @PeterStolz, thank you for reaching out!

Sorry for the inconvenience, we are aware of this issue and plan to address it this week.

Regards,
Diogo

**Comment by PeterStolz** [comment]
Awesome. Thanks for the quick response
