### ISSUE TITLE
IntelliJ Terraform Plugin provides wrong autocompletions

### ISSUE THREAD

**Issue by h3adex** [stackitcloud/terraform-provider-stackit#475]
I'm experiencing an issue and I'm not sure whether it's related to the IntelliJ plugin or this repository. The problem is that autocompletions are not functioning properly in IntelliJ. In contrast, they work perfectly fine in VSCode. Specifically, IntelliJ suggests non-existent resources `stackit_postgres_flex_instance`(see the Screenshot below, correct is `stackit_postgresflex_instance`) and misses suggestions for existing ones, such as `stackit_dns`.

For context, I have only the official StackitCloud Terraform provider installed and have never installed the one from Schwarz-IT.

If you don't have any insights into why this issue is occurring, please feel free to close it, and I'll report it to the Terraform IntelliJ plugin team instead.

Thank you.

PyCharm 2024.1.4 (Community Edition)
Terraform HCL Plugin 241.17890.8

<img width="516" alt="Screenshot 2024-07-22 at 11 56 16" src="https://github.com/user-attachments/assets/381fbceb-35be-4982-8eb7-3d01163423c5">

**Comment by GokceGK** [comment]
Hi @h3adex, 
thanks for getting in touch with us. I verified this and found out that we have no influence about the auto code completion. 
The issue might be on the plugin itself. 

As you also suggested, I am closing the issue.
