### ISSUE TITLE
stackit_ske_cluster module not useable anymore

### ISSUE THREAD

**Issue by Slaizer007** [stackitcloud/terraform-provider-stackit#479]
Hey,

since the new version 0.25.0 the module stackit_ske_cluster is not useable anymore. I tested the same configuration successfully in 0.24.0 and 0.21.0.
While creating the cluster the following error always appears.

Calling API to enable SKE: 403 Forbidden, status code 403, Body:
{"status":403,"message":"Unauthorized"}

**Comment by GokceGK** [comment]
Hi @Slaizer007,

thanks for reaching out to us. 
SKE team has deprecated their service enablement endpoints and that is why we have switched to the Service Enablement API. It might be that Service Enablement API does different permission checks than the SKE endpoints. Could you please verify, if you have the correct permissions for the project you are using? 

Currently I can only reproduce this issue, if I try to create a cluster in a project where I am not a member.

**Comment by Slaizer007** [comment]
hi @GokceGK,

the service account i am using is owner in the STACKIT Project. Also the same terraform code worked as soon as i switched to ver 0.24.0.

**Comment by GokceGK** [comment]
Hi @Slaizer007 , 

can you check if you can call the service enablement endpoints with your service account out of the Terraform Provider (like using Postman)? In the meantime, I will try to verify the issue with Service Enablement team as 403 is coming from their endpoint.

**Comment by GokceGK** [comment]
Hi @Slaizer007, 

The fix was released in [v0.26.2](https://github.com/stackitcloud/terraform-provider-stackit/releases/tag/v0.26.2)
