### ISSUE TITLE
Client.Timeout SKE Kubeconfig Endpoint

### ISSUE THREAD

**Issue by bym0** [stackitcloud/terraform-provider-stackit#571]
Hey,

just tried to upgrade my SKE Cluster but i get a timeout.
![image](https://github.com/user-attachments/assets/f550f8be-5988-459c-9eda-27b579ff2f0a)

Is this just a current error or is there a problem with an endpoint?
I just wanted to set something in a helm chart through terraform. But the plan fails.

**Comment by GokceGK** [comment]
Hi @bym0, 

thanks for reaching out. 
I just have checked the stackit_ske_cluster resource and all operations were successful. This might be a temporary issue. 

Do you still face the same problem?

**Comment by bym0** [comment]
Talked internally with a colleague and it seemed to be a temporary issue. Fixed now and works again :)
