### ISSUE TITLE
support creation of public IP without directly assigning to network interface

### ISSUE THREAD

**Issue by mhenselin** [stackitcloud/terraform-provider-stackit#599]
currently creating a public IP (floating IP) requests for network interface id (optional)

So that would force me to create a NIC with an public IP assigned.

I'd rather create the public IP upfront and attach it at a later to an interface as I then have the ability to rebuild a node and keep the same public IP.

Or is there any other proposed way to do that?

seems to be related: https://github.com/stackitcloud/terraform-provider-stackit/pull/582/files

**Comment by joaopalet** [comment]
Hi @mhenselin,

Thanks for opening the issue.

I'm not sure I fully understood you question. Are you asking if it's possible to create a public IP without associating it to a network interface right away? You can do that by not setting the `network_interface_id` field.

Let me know if this doesn't answer your question.

**Comment by mhenselin** [comment]
thanks. I already realized that the associate resource was added

closing
