### ISSUE TITLE
Missing required attribute region for stackit_postgresflex_instance

### ISSUE THREAD

**Issue by docbyte86** [stackitcloud/terraform-provider-stackit#87]
Error:

│ Error: Error configuring API client
│ 
│   with module.db.stackit_postgresflex_instance.database,
│   on .terraform/modules/db/main.tf line 5, in resource "stackit_postgresflex_instance" "database":
│    5: resource "stackit_postgresflex_instance" "database" {
│ 
│ Configuring client: configuring region: no region was provided, available
│ regions are: [eu01]

The required attribute region is missing in the documentation of version 0.5.0
[stackit_postgresflex_instance (Resource)](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs/resources/postgresflex_instance)

If I set region as attribute like:

resource "stackit_postgresflex_instance" "database" {
  acl             = var.database_acl
  backup_schedule = var.database_backup_schedule
  flavor          = var.database_flavor
  name            = var.database_name
  project_id      = var.database_project_id
  replicas        = var.database_replicas
  storage         = var.database_storage
  version         = var.database_version
  region          = var.database_region
}

variable "database_region" {
  description = "The region where the instance runs in."
  type        = string
  default     = "eu01"
}

I'll get the following error:

│ Error: Unsupported argument
│ 
│   on .terraform/modules/db/main.tf line 14, in resource "stackit_postgresflex_instance" "database":
│   14:   region          = var.database_region
│ 
│ An argument named "region" is not expected here.

**Comment by hcsa73** [comment]
Hello, thanks for your feedback!

The `region` argument is set in the provider configuration, as described [here](https://registry.terraform.io/providers/stackitcloud/stackit/latest/docs):
```terraform
provider "stackit" {
    region = "eu01"
}
```

This argument is required to access some of the resources. However, neither the error message you found nor the PostgresFlex documentation page describe this clearly. We'll make changes to address this.
